model:
  pretrained_clip_name: "ViT-B/32"
  freeze_layer_num: 0
  linear_patch: "2d" # linear projection of flattened patches. ["2d", "3d"]
  sim_header: "seqTransf" # choice a similarity header. ["meanP", "seqLSTM", "seqTransf", "tightTransf"]
  cross_model: "cross-base"
  loose_type: True
  cross_num_hidden_layers: 4

datasets:
  data_type: "msrvtt"
  train_csv: "data/datasets/msrvtt/Annotations/MSRVTT_train.9k.csv"
  val_csv: "data/datasets/msrvtt/Annotations/MSRVTT_JSFUSION_test.csv"
  test_csv: "data/datasets/msrvtt/Annotations/MSRVTT_JSFUSION_test.csv"
  data_path: "data/datasets/msrvtt/Annotations/MSRVTT_data.json"
  video_path: "data/datasets/msrvtt/VideoData"

  num_thread_reader: 8
  max_words: 32
  max_frames: 12
  feature_framerate: 1
  expand_msrvtt_sentences: True
  train_frame_order: 0 # Frame order, 0: ordinary order; 1: reverse order; 2: random order.
  eval_frame_order: 0
  slice_framepos: 2 # "0: cut from head frames; 1: cut from tail frames; 2: extract frames uniformly."


distillation:
  beta: 1.0
  distill_method: "pear"
  fine_method: "ce"
  teacher_num: 2
  teacher1_name: "XCLIP"
  init_teacher1_model: "data/teacher_checkpoints/xclip/msrvtt-9k_xclip_model.bin"
  teacher2_name: "TS2Net"
  init_teacher1_model: "data/teacher_checkpoints/ts2net/msrvtt-9k_ts2net_model.bin"

train:
  overwrite: False
  seed: 42
  lr: 0.0001
  coef_lr: 0.001
  epochs: 10
  batch_size: 120
  batch_size_val: 20
  lr_decay: 0.9
  n_display: 10
  warmup_proportion: 0.1
  gradient_accumulation_steps: 1
  output_dir: "data/datasets/msrvtt/Saves/msrvtt-9k_xclip+ts2net-as-teacher_vit32"

eval:
  init_model: "" # best model checkpoint for evaluation